environment:
  CURL_VERSION: 7.56.1
  CmakeGenerator: Visual Studio 14 2015
  DepsPath32: $(APPVEYOR_BUILD_FOLDER)\dependencies2015\win32
  DepsPath64: $(APPVEYOR_BUILD_FOLDER)\dependencies2015\win64
  BuildPath32: $(APPVEYOR_BUILD_FOLDER)\build32
  BuildPath64: $(APPVEYOR_BUILD_FOLDER)\build64
  InstallPath: $(APPVEYOR_BUILD_FOLDER)\packed_build
  BuildConfig: RelWithDebInfo

install:
  - ps: $env:Artifact="$(git describe).zip"
  - cmd: ECHO "Artifact File Name: %Artifact%"
  - git submodule update --init --recursive
  - if exist dependencies2015.zip (curl -kLO https://obsproject.com/downloads/dependencies2015.zip -f --retry 5 -z dependencies2015.zip) else (curl -kLO https://obsproject.com/downloads/dependencies2015.zip -f --retry 5 -C -)
  - 7z x dependencies2015.zip -odependencies2015
  - move "C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\d3d11on12*" "C:\Program Files (x86)\Windows Kits\8.1\Include\um"
  - move "C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\d3d12*" "C:\Program Files (x86)\Windows Kits\8.1\Include\um"
  - move "C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\shared\dxgi*" "C:\Program Files (x86)\Windows Kits\8.1\Include\shared"
  - mkdir "%BuildPath32%"
  - mkdir "%BuildPath64%"

build_script:
  - cmake -G"%CmakeGenerator%" -H"%APPVEYOR_BUILD_FOLDER%" -B"%BuildPath32%" -DCMAKE_INSTALL_PREFIX="%InstallPath%" -DENABLE_UI=false -DCOPIED_DEPENDENCIES=false -DCOPY_DEPENDENCIES=true -DBUILD_CAPTIONS=true -DCOMPILE_D3D12_HOOK=true
  - cmake -G"%CmakeGenerator%" -H"%APPVEYOR_BUILD_FOLDER%" -B"%BuildPath64%" -A x64 -DCMAKE_INSTALL_PREFIX="%InstallPath%" -DENABLE_UI=false -DCOPIED_DEPENDENCIES=false -DCOPY_DEPENDENCIES=true -DBUILD_CAPTIONS=true -DCOMPILE_D3D12_HOOK=true
  - cmake --build "%BuildPath32%\plugins\win-capture\get-graphics-offsets" --config "%BuildConfig%" --target install
  - cmake --build "%BuildPath32%\plugins\win-capture\graphics-hook" --config "%BuildConfig%" --target install
  - cmake --build "%BuildPath32%\plugins\win-capture\inject-helper" --config "%BuildConfig%" --target install
  - cmake --build "%BuildPath64%" --config "%BuildConfig%" --target install

after_build:
  - 7z a "%Artifact%" "%InstallPath%\*"

artifacts:
  - path: "$(Artifact)"
    name: Packed Artifact

test: off

cache:
  - dependencies2015.zip
